# Llama3 DocChat SFT Stage 2

train_input:
  data_processor: "GptHDF5MapDataProcessor"
  mixture:
    - data_dir: processed_datasets/drop/with_vsl_hdf5
      weight: 0.014350383
    - data_dir: processed_datasets/narrativeqa/with_vsl_hdf5
      weight: 0.045030383
    - data_dir: processed_datasets/newsqa/with_vsl_hdf5
      weight: 0.046302585
    - data_dir: processed_datasets/quoref/with_vsl_hdf5
      weight: 0.007118324
    - data_dir: processed_datasets/ropes/with_vsl_hdf5
      weight: 0.003401013
    - data_dir: processed_datasets/sft/with_vsl_hdf5
      weight: 0.070348585
    - data_dir: processed_datasets/skginstruct/with_vsl_hdf5
      weight: 0.079142158
    - data_dir: processed_datasets/squad1.1/with_vsl_hdf5
      weight: 0.012987991
    - data_dir: processed_datasets/squad2.0/with_vsl_hdf5
      weight: 0.012986938
    - data_dir: processed_datasets/synthetic_convqa_answer/with_vsl_hdf5
      weight: 0.244831885
    - data_dir: processed_datasets/synthetic_convqa_no_answer/with_vsl_hdf5
      weight: 0.014109896
    - data_dir: processed_datasets/tatqa_arithmetic/with_vsl_hdf5
      weight: 0.055826447
    - data_dir: processed_datasets/tatqa_arithmetic_cot/with_vsl_hdf5
      weight: 0.027399127
    - data_dir: processed_datasets/tatqa_others/with_vsl_hdf5
      weight: 0.025976015
    - data_dir: processed_datasets/hybridial/with_vsl_hdf5
      weight: 0.258964748
    - data_dir: processed_datasets/numina_math_cot/with_vsl_hdf5
      weight: 0.081223519
  batch_size: 5
  repeat: True
  shuffle: False
  shuffle_seed: 1337
  num_workers: 8
  prefetch_factor: 10
  persistent_workers: True
  use_vsl: True

model:
    # Embedding
    vocab_size: 128256
    hidden_size: 4096
    position_embedding_type: "rotary"
    pos_scaling_factor: 1.0
    rope_theta: 500000.0
    rotary_dim: 128
    share_embedding_weights: false
    max_position_embeddings: 8192
    embedding_dropout_rate: 0.0
    embedding_layer_norm: false

    # Decoder
    num_hidden_layers: 32
    dropout_rate: 0.0
    layer_norm_epsilon: 1.0e-5
    norm_type: "rmsnorm"

    # Decoder - Attention
    num_heads: 32
    attention_type: "scaled_dot_product"
    attention_module: "multiquery_attention"
    attention_dropout_rate: 0.0
    use_projection_bias_in_attention: false
    use_ffn_bias_in_attention: false
    extra_attention_params:
        num_kv_groups: 8

    # Decoder - ffn
    filter_size: 14336
    nonlinearity: "swiglu"
    use_ffn_bias: false

    # Task-specific
    use_bias_in_output: false
    loss_scaling: "num_tokens"
    loss_weight: 1.0

    # Initializer
    initializer_range: 0.02

    # Cerebras parameters
    mixed_precision: True
    fp16_type: "cbfloat16"
  
optimizer:
    optimizer_type: "AdamW"
    betas: [0.9, 0.95]
    correct_bias: True
    weight_decay: 0.1
    learning_rate:
        - scheduler: "CosineDecay"
          initial_learning_rate: 6.0e-07
          end_learning_rate: 2.0e-8
          total_iters: 4555
    max_gradient_norm: 1.0
    log_summaries: True
    loss_scaling_factor: "dynamic"

runconfig:
    max_steps: 4555
    checkpoint_steps: 2300
    log_steps: 1
    save_initial_checkpoint: False
    precision_opt_level: 1
    seed: 1
