# Cerebras Dragon-DocChat model, 220M parameters (2*110M for BERT question and passage encoder), max_seq_length 512

train_input:
    data_processor: "DPRHDF5DataProcessor"
    data_dir: "processed_datasets/syntheticConvQA_hdf5/"
    batch_size: 64
    micro_batch_size: null
    shuffle: True
    shuffle_seed: 1
    shuffle_buffer: 16384
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True
    
model:
    q_encoder: &base_model
        add_pooling_layer: false
        attention_dropout_rate: 0.1
        dropout_rate: 0.1
        encoder_nonlinearity: gelu
        filter_size: 3072
        hidden_size: 768
        initializer_range: 0.02
        layer_norm_epsilon: 1.0e-12
        max_position_embeddings: 512
        mixed_precision: true
        mlm_nonlinearity: gelu
        num_heads: 12
        num_hidden_layers: 12
        pooler_nonlinearity: tanh
        position_embedding_type: learned
        share_embedding_weights: true
        vocab_size: 30522
    ctx_encoder:
        <<: *base_model
    
    mutual_information: true
    pooler_type: cls
    compute_eval_metrics: False
    softmax_temperature: 1
    use_biencoder: true
    
optimizer:
    optimizer_type: "Adamw"
    weight_decay: 0.01
    loss_scaling_factor: "dynamic"
    max_gradient_norm: 1.0
    learning_rate:
        - scheduler: "Linear"
          initial_learning_rate: 0.0
          total_iters: 450
          end_learning_rate: 3.0e-5
        - scheduler: "Linear"
          initial_learning_rate: 3.0e-5
          end_learning_rate: 1.5e-5
          total_iters: 450

runconfig:
    # (28732 samples per epoch * 2 epochs / 64 samples per batch)
    max_steps: 900
    log_steps: 1
    # checkpoint each epoch
    checkpoint_steps: 450
    save_initial_checkpoint: True
    seed: 1
    model_dir: "./model_dir"